# Generated by Django 4.0.6 on 2022-07-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('test', models.CharField(max_length=50, verbose_name='gh')),
            ],
        ),
    ]
