# Generated by Django 4.0.6 on 2022-07-30 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('register_id', models.AutoField(primary_key=True, serialize=False, verbose_name='')),
                ('country', models.CharField(max_length=50, verbose_name='')),
                ('state', models.CharField(max_length=50, verbose_name='')),
                ('email', models.EmailField(max_length=254, verbose_name='')),
                ('phone', models.CharField(max_length=50, verbose_name='')),
                ('frist_name', models.CharField(max_length=50, verbose_name='')),
                ('last_name', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
