# Generated by Django 4.0.6 on 2022-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_register_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='country',
            field=models.CharField(max_length=30, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='register',
            name='frist_name',
            field=models.CharField(max_length=30, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='register',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=15, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(max_length=30, verbose_name=''),
        ),
    ]
