# Generated by Django 4.0.6 on 2022-08-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_register_country_alter_register_frist_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
